swarm_cover_v1:
  n_envs: 8
  n_timesteps: !!float 1e5
  policy: 'MlpPolicy'
  n_steps: 32
  batch_size: 256
  gae_lambda: 0.8
  gamma: 0.98
  n_epochs: 15
  ent_coef: 0.0
  learning_rate: lin_7.e-4
  clip_range: lin_0.2
