name: camoc
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anyio=2.2.0
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=21.2.0
  - babel=2.9.1
  - backcall=0.2.0
  - bleach=4.1.0
  - brotlipy=0.7.0
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - cryptography=36.0.0
  - debugpy=1.5.1
  - decorator=5.1.0
  - defusedxml=0.7.1
  - entrypoints=0.3
  - idna=3.3
  - importlib_metadata=4.8.2
  - ipykernel=6.4.1
  - ipython=7.29.0
  - ipython_genutils=0.2.0
  - jedi=0.18.0
  - jinja2=3.0.2
  - json5=0.9.6
  - jsonschema=3.2.0
  - jupyter_client=7.1.0
  - jupyter_core=4.9.1
  - jupyter_server=1.4.1
  - jupyterlab=3.2.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.10.2
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - markupsafe=2.0.1
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - nbclassic=0.2.6
  - nbclient=0.5.3
  - nbconvert=6.3.0
  - nbformat=5.1.3
  - ncurses=6.3
  - nest-asyncio=1.5.1
  - notebook=6.4.6
  - openssl=1.1.1m
  - packaging=21.3
  - pandocfilters=1.4.3
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.2.4
  - prometheus_client=0.12.0
  - prompt-toolkit=3.0.20
  - ptyprocess=0.7.0
  - pycparser=2.21
  - pygments=2.10.0
  - pyopenssl=21.0.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.8.12
  - python-dateutil=2.8.2
  - pyzmq=22.3.0
  - readline=8.1.2
  - requests=2.27.1
  - send2trash=1.8.0
  - setuptools=58.0.4
  - six=1.16.0
  - sniffio=1.2.0
  - sqlite=3.37.0
  - terminado=0.9.4
  - testpath=0.5.0
  - tk=8.6.11
  - tornado=6.1
  - traitlets=5.1.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.7.0
  - zlib=1.2.11
  - pip:
    - absl-py==1.0.0
    - atari-py==0.2.9
    - cachetools==4.2.4
    - cffi==1.15.0
    - charset-normalizer==2.0.10
    - chess==1.7.0
    - cloudpickle==1.6.0
    - cycler==0.11.0
    - fonttools==4.28.5
    - google-auth==2.3.3
    - google-auth-oauthlib==0.4.6
    - grpcio==1.43.0
    - gym==0.21.0
    - hanabi-learning-environment==0.0.1
    - importlib-metadata==4.10.0
    - kiwisolver==1.3.2
    - magent==0.1.14
    - markdown==3.3.6
    - matplotlib==3.5.1
    - multi-agent-ale-py==0.1.11
    - numpy==1.22.1
    - oauthlib==3.1.1
    - opencv-python==3.4.17.61
    - pandas==1.3.5
    - pettingzoo==1.14.0
    - pillow==9.0.0
    - protobuf==3.19.3
    - psutil==5.9.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pygame==2.1.0
    - pyglet==1.5.21
    - pymunk==6.2.0
    - pyparsing==3.0.6
    - pytz==2021.3
    - requests-oauthlib==1.3.0
    - rlcard==1.0.4
    - rsa==4.8
    - scipy==1.7.3
    - git+https://github.com/rytse/stable-baselines3.git
    - supersuit==3.3.2
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - termcolor==1.1.0
    - torch==1.10.1
    - typing-extensions==4.0.1
    - urllib3==1.26.8
    - werkzeug==2.0.2
    - jax==0.2.23
